### PR TITLE
Recreate coilset optimisation problem example

### LINKED ISSUE #1538: Recreate coilset optimisation problem example
## Description of issue / requirement to address

The coilset optimisation examples will be removed in #1536 (see #1523). It is currently broken on develop also

## Proposed solution

Create a coilset optimisation example

## Alternative solutions

None

## Additional context

Removed as no longer works in current form

### PR DESCRIPTION
**Pull request by athoynilimanew**
## Linked Issues

Closes #1538

## Description

Revive the old coilset optimization problem example 

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Review by geograham — DISMISSED** [review]
All working as expected! 

There are a couple of sections in the text that got missed in the update, see 'BoundedCurrentCOP'.  

Also could you add a line stating what symmetric circuits are for?

**Comment by athoynilimanew** [comment]
> There are a couple of sections in the text that got missed in the update, see 'BoundedCurrentCOP'.

Now that I check this again, I can see Bluemira still have the old optimization modules as well as the new ones. Which optimization module should this example refer to?

**Comment by athoynilimanew** [comment]
> All working as expected!
> 
> There are a couple of sections in the text that got missed in the update, see 'BoundedCurrentCOP'.
> 
> Also could you add a line stating what symmetric circuits are for?

line added

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 1]
```diff
@@ -0,0 +1,447 @@
...
+#
+# This tutorial finds a Spherical Tokamak (ST) equilibrium in a
+# double null configuration,
+# using a constrained optimisation method with bound constraints on
+# the maximum coil currents and some additional constraints.
+#
+
+# %%[markdown]
+
+# # Introduction
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:39]:
```suggestion
# ## Introduction
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 2]
```diff
@@ -0,0 +1,447 @@
...
+
+# In this example, we will outline how to specify a `CoilsetOptimisationProblem`
+# that specifies how an 'optimised' coilset state is found during the Free Boundary
+# Equilibrium solve step.
+
+# # Imports
+
+# Import necessary equilbria module definitions.
+
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:48]:
```suggestion
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 3]
```diff
@@ -0,0 +1,447 @@
...
+    MagneticConstraintSet,
+)
+from bluemira.equilibria.optimisation.problem import (
+    TikhonovCurrentCOP,
+    UnconstrainedTikhonovCurrentGradientCOP,
+)
+from bluemira.equilibria.profiles import CustomProfile
+from bluemira.equilibria.solve import DudsonConvergence, PicardIterator
+
+# %%[markdown]
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:70]: This change needs to happen in quite a few places otherwise it doesnt render properly
```suggestion
# %% [markdown]
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 4]
```diff
@@ -0,0 +1,447 @@
...
+
+# # CoilsetOptimisationProblem
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:72]:
```suggestion
# ## The `CoilsetOptimisationProblem` class
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 5]
```diff
@@ -0,0 +1,447 @@
...
+
+# The `CoilsetOptimisationProblem` class is intended to be the abstract
+# base class for coilset optimisation problems across Bluemira.
+#
+# *Remember: There are currently two optimization modules in Bluemira
+# Develop, and this example intends to illustrate the use of the newest
+# one in `bluemira.equilibria.optimisation`*
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:79]: We don't need to even tell people about the old one. The same reason we don't have any examples using old functionality
```suggestion
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 6]
```diff
@@ -0,0 +1,447 @@
...
+#
+# The goal of the `CoilsetOptimisationProblem` is to be able to return
+# an optimised coilset, judged according to the provided objective,
+# subject to the set of constraints, using a numerical search algorithm
+# subject to optimiser conditions and optimiser parameters.
+#
+# Subclasses of `CoilsetOptimisationProblem` thus should provide an
+# `optimise()` method that returns an optimised coilset object,
+#  optimised according to a specific objective function
+# for that subclass.
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:89]:
```suggestion
# `optimise()` method that returns the `CoilsetOptimiserResult`,
# containing the coilset optimised according to a specific objective
# function for that subclass.
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 7]
```diff
@@ -0,0 +1,447 @@
...
+#
+# ## Ingredients for a coilset optimization problem
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:91]: British spelling please, here and elsewhere
```suggestion
# ### Ingredients for a Coilset optimisation problem
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 8]
```diff
@@ -0,0 +1,447 @@
...
+# - **Coilset**: the set of PF coils we want to optimize
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:92]: It is usually PF coils we're optimising but not explicitly
```suggestion
# - **Coilset**: the set of coils we want to optimise
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 9]
```diff
@@ -0,0 +1,447 @@
...
+
+legs_isoflux = IsofluxConstraint(
+    x_legs, z_legs, ref_x=x_lcfs[2], ref_z=z_lcfs[2], constraint_value=0.1
+)
+
+magnetic_targets = MagneticConstraintSet([lcfs_isoflux, legs_isoflux])
+
+# %%[markdown]
+
+# ## Optimisation algorithm, conditions and parameters
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:290]:
```suggestion
# ## Optimisation Algorithm, Conditions and Parameters
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 10]
```diff
@@ -0,0 +1,447 @@
...
+constrained_iterator()
+
+f, ax = plt.subplots()
+eq.plot(ax=ax)
+eq.coilset.plot(ax=ax, subcoil=False, label=True)
+magnetic_targets.plot(ax=ax)
+plt.show()
+
+# %%[markdown]
+# You can now re-do this tutorial with other constraints of your choice
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:446]:
```suggestion
# You can now re-do this tutorial with other constraints of your choice.
# See `bluemira.equilibria.optimisation.constraints` for some prebuilt constraints.
```

**Review by je-cook — CHANGES_REQUESTED** [review]
A few markdown based fixes to do here. Also the actual problem doesnt converge. Either reduce the tolerance, increase the number of iterations etc. to get some sort of convergence. Possibly setting the discretisation of the coils might also help with the downside of slowing down the problem.

image

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py (hunk 3 above)
Comment (athoynilimanew) [reply examples/equilibria/coilset_opt_problem_tutorial.ex.py]: done

File: documentation/source/examples.rst [hunk 11]
```diff
@@ -24,9 +24,7 @@ Equilibria Examples
     examples/equilibria/fixed_boundary
     examples/equilibria/Spherical_Approximation_how_it_works
     examples/equilibria/spherical_harmonic_approximation_basic_function_check
-
-Geometry Examples
-^^^^^^^^^^^^^^^^^
+    examples/equilibria/coilset_opt_problem_tutorial
```
[the remark this answers is not in the document]
Comment (athoynilimanew) [reply documentation/source/examples.rst]: done

**Comment by athoynilimanew** [comment]
> A few markdown based fixes to do here. Also the actual problem doesnt converge. Either reduce the tolerance, increase the number of iterations etc. to get some sort of convergence. Possibly setting the discretisation of the coils might also help with the downside of slowing down the problem.
> 
> image

Not sure: In my computer it is converging: 

image

image

**Comment by athoynilimanew** [comment]
> A few markdown based fixes to do here. Also the actual problem doesnt converge. Either reduce the tolerance, increase the number of iterations etc. to get some sort of convergence. Possibly setting the discretisation of the coils might also help with the downside of slowing down the problem.
> 
> image

Could you please check now?

**Comment by je-cook** [comment]
> Could you please check now?

Nope 
image

File: documentation/source/examples.rst [hunk 12]
```diff
@@ -24,9 +24,10 @@ Equilibria Examples
     examples/equilibria/fixed_boundary
     examples/equilibria/Spherical_Approximation_how_it_works
     examples/equilibria/spherical_harmonic_approximation_basic_function_check
+    examples/equilibria/coilset_opt_problem_tutorial
 
 Geometry Examples
-^^^^^^^^^^^^^^^^^
+^^^^^^^^^^^^^^^^^^^^^^^
```
Comment (je-cook) [inline documentation/source/examples.rst:30]:
```suggestion
^^^^^^^^^^^^^^^^^
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 13]
```diff
@@ -0,0 +1,440 @@
...
+#
+# - **opt_algorithm**, **opt_conditions** and **opt_parameters**
+#
+# - **max_currents**: Maximum allowed current for each independent coil
+# current in coilset [A].
+#
+# - **constraints**: Optional list of `UpdatableConstraint` objects
+#
+# %%
+# %% [markdown]
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:137]:
```suggestion
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 14]
```diff
@@ -0,0 +1,440 @@
...
+# Care must also be taken to ensure the termination criteria for the
+# optimisation are suitable. Otherwise, the optimisation may never
+# stop running if tolerances are too tight, or may stop early and
+# return poorly optimised states if the maximum number of evaluations
+# is too low or tolerances are too large.
+#
+# **We will directly input the optimisation algorithm, conditions and**
+# **parameters when defining the `TikhonovCurrentCOP`**
+# %%
+# %% [markdown]
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:305]:
```suggestion
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 15]
```diff
@@ -0,0 +1,440 @@
...
+f, ax = plt.subplots()
+eq.plot(ax=ax)
+eq.coilset.plot(ax=ax, subcoil=False, label=True)
+magnetic_targets.plot(ax=ax)
+plt.show()
+
+# %% [markdown]
+# You can now re-do this tutorial with other constraints of your choice.
+# See `bluemira.equilibria.optimisation.constraints` for some prebuilt constraints.
+# %%
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:440]:
```suggestion
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 16]
```diff
@@ -0,0 +1,440 @@
...
+# some require additional parameters. Check the NLOpt API documentation
+# for more details.
+#
+# Care must also be taken to ensure the termination criteria for the
+# optimisation are suitable. Otherwise, the optimisation may never
+# stop running if tolerances are too tight, or may stop early and
+# return poorly optimised states if the maximum number of evaluations
+# is too low or tolerances are too large.
+#
+# **We will directly input the optimisation algorithm, conditions and**
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:302]:
```suggestion
# **Below we will directly input the optimisation algorithm, conditions and**
```

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 17]
```diff
@@ -0,0 +1,440 @@
...
+f, ax = plt.subplots()
+eq.plot(ax=ax)
+eq.coilset.plot(ax=ax, subcoil=False, label=True)
+magnetic_targets.plot(ax=ax)
+plt.show()
+
+# %% [markdown]
+
+# ## Constrained Optimisation
+# ### Constraints
```
Comment (je-cook) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:383]:
```suggestion
# ## Constrained Optimisation
```

**Review by je-cook — CHANGES_REQUESTED** [review]
A few more minor but more generally I'm not sure this flows 100% in the example from `## Optimisation Algorithm, Conditions and Parameters` onwards the headers seem to be a bit jarringly indented. Could you look at the rendered version and try and rearrange some of the sections (not the code just really the headers)?

Also still doesnt converge. Please read the warning messages

**Comment by athoynilimanew** [comment]
> A few more minor but more generally I'm not sure this flows 100% in the example from `## Optimisation Algorithm, Conditions and Parameters` onwards the headers seem to be a bit jarringly indented. Could you look at the rendered version and try and rearrange some of the sections (not the code just really the headers)?
> 
> Also still doesnt converge. Please read the warning messages

Thanks. I think I will take a look on it on Monday (I am on holiday tomorrow). Apologies for delaying.

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 18]
```diff
@@ -0,0 +1,434 @@
...
+unconstrained_cop = UnconstrainedTikhonovCurrentGradientCOP(
+    coilset, eq, magnetic_targets, gamma=1e-8
+)
+unconstrained_iterator = PicardIterator(
+    eq,
+    unconstrained_cop,
+    fixed_coils=True,
+    plot=False,
+    relaxation=0.3,
+    convergence=DudsonConvergence(1e-4),
```
Comment (geograham) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:340]: Can change to 1e-6 (and will still work).

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 19]
```diff
@@ -0,0 +1,434 @@
...
+    constraints=[field_constraints, x_point, lcfs_isoflux],
+)
+constrained_iterator = PicardIterator(
+    eq,
+    opt_problem,
+    fixed_coils=True,
+    plot=False,
+    relaxation=0.1,
+    maxiter=100,
+    convergence=DudsonConvergence(1e-4),
```
Comment (geograham) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:421]: Can change to 1e-6.

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 20]
```diff
@@ -0,0 +1,434 @@
...
+    tolerance=1e-2,  # [T]
+)
+
+# %% [markdown]
+# Now we have a better starting `Equilibrium` for our constrained optimisation
+# We now initialise the TikhonovCurrentCOP and perform the optimisation:
+#
+# %%
+opt_problem = TikhonovCurrentCOP(
+    coilset=coilset,
```
Comment (geograham) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:404]: coilset=coilset -> coilset=eq.coilset

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py [hunk 21]
```diff
@@ -0,0 +1,434 @@
...
+    eq=eq,
+    targets=magnetic_targets,
+    gamma=1e-8,
+    opt_algorithm="COBYLA",
+    opt_conditions={"max_eval": 400},
+    opt_parameters={"initial_step": 0.01},
+    max_currents=3.0e7,
+    constraints=[field_constraints, x_point, lcfs_isoflux],
```
Comment (geograham) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:412]: constraints=[field_constraints, x_point, lcfs_isoflux] -> constraints=[field_constraints, x_point, lcfs_isoflux, legs_isoflux]

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py
Comment (geograham) [inline examples/equilibria/coilset_opt_problem_tutorial.ex.py:1]: Hey, it converges for me once you fix the two small errors (see below), plus you can have a smaller value for the convergence of 1e-6 .

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py (hunk 21 above)
Comment (athoynilimanew) [reply examples/equilibria/coilset_opt_problem_tutorial.ex.py:412]: done

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py (hunk 19 above)
Comment (athoynilimanew) [reply examples/equilibria/coilset_opt_problem_tutorial.ex.py:421]: done

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py (hunk 20 above)
Comment (athoynilimanew) [reply examples/equilibria/coilset_opt_problem_tutorial.ex.py:404]: done

File: examples/equilibria/coilset_opt_problem_tutorial.ex.py (hunk 18 above)
Comment (athoynilimanew) [reply examples/equilibria/coilset_opt_problem_tutorial.ex.py:340]: done

**Comment by athoynilimanew** [comment]
It now converges after applying relative tolerances as per @geograham's suggestions
